package card

// ID 牌的ID类型
type ID int

// 麻将牌面对应的数值定义
const (
	MAHJONG_PLACEHOLDER ID = iota // 空，占位，无意义
	MAHJONG_CRAK1                 // 万(1 ~ 9)
	MAHJONG_CRAK2
	MAHJONG_CRAK3
	MAHJONG_CRAK4
	MAHJONG_CRAK5
	MAHJONG_CRAK6
	MAHJONG_CRAK7
	MAHJONG_CRAK8
	MAHJONG_CRAK9
	MAHJONG_CRAK_PLACEHOLDER // 10, 占位，无意义
	MAHJONG_BAM1             // 条(11 ~ 19)
	MAHJONG_BAM2
	MAHJONG_BAM3
	MAHJONG_BAM4
	MAHJONG_BAM5
	MAHJONG_BAM6
	MAHJONG_BAM7
	MAHJONG_BAM8
	MAHJONG_BAM9
	MAHJONG_BAM_PLACE_HOLDER // 20, 占位，无意义
	MAHJONG_DOT1             // 筒(21 ~ 29)
	MAHJONG_DOT2
	MAHJONG_DOT3
	MAHJONG_DOT4
	MAHJONG_DOT5
	MAHJONG_DOT6
	MAHJONG_DOT7
	MAHJONG_DOT8
	MAHJONG_DOT9
	MAHJONG_DOT_PLACEHOLDER // 30, 占位，无意义

	MAHJONG_EAST  ID = 31 // 东南北西 (31 ~ 34)
	MAHJONG_NORTH ID = 32
	MAHJONG_SOUTH ID = 33
	MAHJONG_WEST  ID = 34

	MAHJONG_GREE  ID = 41 // 发财、红中、白板 (35 ~ 37) -> NOTE: Values are 41, 42, 43
	MAHJONG_RED   ID = 42
	MAHJONG_WHITE ID = 43

	MAHJONG_SEASON1 ID = 51 // 春夏秋冬（51 ~ 54）
	MAHJONG_SEASON2 ID = 52
	MAHJONG_SEASON3 ID = 53
	MAHJONG_SEASON4 ID = 54

	MAHJONG_FLOWER1 ID = 61 // 花色 (61 ~ 64)
	MAHJONG_FLOWER2 ID = 62
	MAHJONG_FLOWER3 ID = 63
	MAHJONG_FLOWER4 ID = 64
)

// SideCards 边张
var SideCards = []ID{MAHJONG_CRAK1, MAHJONG_CRAK9, MAHJONG_BAM1, MAHJONG_BAM9, MAHJONG_DOT1, MAHJONG_DOT9}

// LeftSideCards 左边张
var LeftSideCards = []ID{MAHJONG_CRAK1, MAHJONG_BAM1, MAHJONG_DOT1}

// RightSideCards 右边张
var RightSideCards = []ID{MAHJONG_CRAK9, MAHJONG_BAM9, MAHJONG_DOT9}

// SideNeighborCards 邻边张
var SideNeighborCards = []ID{MAHJONG_CRAK2, MAHJONG_CRAK8, MAHJONG_BAM2, MAHJONG_BAM8, MAHJONG_DOT2, MAHJONG_DOT8}

// LeftSideNeighborCards 左邻边张
var LeftSideNeighborCards = []ID{MAHJONG_CRAK2, MAHJONG_BAM2, MAHJONG_DOT2}

// RightSideNeighborCards 右邻边张
var RightSideNeighborCards = []ID{MAHJONG_CRAK8, MAHJONG_BAM8, MAHJONG_DOT8}

// MahjongCards108 108 张牌
var MahjongCards108 = []ID{
	// 万
	MAHJONG_CRAK1, MAHJONG_CRAK1, MAHJONG_CRAK1, MAHJONG_CRAK1,
	MAHJONG_CRAK2, MAHJONG_CRAK2, MAHJONG_CRAK2, MAHJONG_CRAK2,
	MAHJONG_CRAK3, MAHJONG_CRAK3, MAHJONG_CRAK3, MAHJONG_CRAK3,
	MAHJONG_CRAK4, MAHJONG_CRAK4, MAHJONG_CRAK4, MAHJONG_CRAK4,
	MAHJONG_CRAK5, MAHJONG_CRAK5, MAHJONG_CRAK5, MAHJONG_CRAK5,
	MAHJONG_CRAK6, MAHJONG_CRAK6, MAHJONG_CRAK6, MAHJONG_CRAK6,
	MAHJONG_CRAK7, MAHJONG_CRAK7, MAHJONG_CRAK7, MAHJONG_CRAK7,
	MAHJONG_CRAK8, MAHJONG_CRAK8, MAHJONG_CRAK8, MAHJONG_CRAK8,
	MAHJONG_CRAK9, MAHJONG_CRAK9, MAHJONG_CRAK9, MAHJONG_CRAK9,

	// 筒
	MAHJONG_DOT1, MAHJONG_DOT1, MAHJONG_DOT1, MAHJONG_DOT1,
	MAHJONG_DOT2, MAHJONG_DOT2, MAHJONG_DOT2, MAHJONG_DOT2,
	MAHJONG_DOT3, MAHJONG_DOT3, MAHJONG_DOT3, MAHJONG_DOT3,
	MAHJONG_DOT4, MAHJONG_DOT4, MAHJONG_DOT4, MAHJONG_DOT4,
	MAHJONG_DOT5, MAHJONG_DOT5, MAHJONG_DOT5, MAHJONG_DOT5,
	MAHJONG_DOT6, MAHJONG_DOT6, MAHJONG_DOT6, MAHJONG_DOT6,
	MAHJONG_DOT7, MAHJONG_DOT7, MAHJONG_DOT7, MAHJONG_DOT7,
	MAHJONG_DOT8, MAHJONG_DOT8, MAHJONG_DOT8, MAHJONG_DOT8,
	MAHJONG_DOT9, MAHJONG_DOT9, MAHJONG_DOT9, MAHJONG_DOT9,

	// 条
	MAHJONG_BAM1, MAHJONG_BAM1, MAHJONG_BAM1, MAHJONG_BAM1,
	MAHJONG_BAM2, MAHJONG_BAM2, MAHJONG_BAM2, MAHJONG_BAM2,
	MAHJONG_BAM3, MAHJONG_BAM3, MAHJONG_BAM3, MAHJONG_BAM3,
	MAHJONG_BAM4, MAHJONG_BAM4, MAHJONG_BAM4, MAHJONG_BAM4,
	MAHJONG_BAM5, MAHJONG_BAM5, MAHJONG_BAM5, MAHJONG_BAM5,
	MAHJONG_BAM6, MAHJONG_BAM6, MAHJONG_BAM6, MAHJONG_BAM6,
	MAHJONG_BAM7, MAHJONG_BAM7, MAHJONG_BAM7, MAHJONG_BAM7,
	MAHJONG_BAM8, MAHJONG_BAM8, MAHJONG_BAM8, MAHJONG_BAM8,
	MAHJONG_BAM9, MAHJONG_BAM9, MAHJONG_BAM9, MAHJONG_BAM9,
}

// MahjongCards72 72 张牌
var MahjongCards72 = []ID{
	// 筒
	MAHJONG_DOT1, MAHJONG_DOT1, MAHJONG_DOT1, MAHJONG_DOT1,
	MAHJONG_DOT2, MAHJONG_DOT2, MAHJONG_DOT2, MAHJONG_DOT2,
	MAHJONG_DOT3, MAHJONG_DOT3, MAHJONG_DOT3, MAHJONG_DOT3,
	MAHJONG_DOT4, MAHJONG_DOT4, MAHJONG_DOT4, MAHJONG_DOT4,
	MAHJONG_DOT5, MAHJONG_DOT5, MAHJONG_DOT5, MAHJONG_DOT5,
	MAHJONG_DOT6, MAHJONG_DOT6, MAHJONG_DOT6, MAHJONG_DOT6,
	MAHJONG_DOT7, MAHJONG_DOT7, MAHJONG_DOT7, MAHJONG_DOT7,
	MAHJONG_DOT8, MAHJONG_DOT8, MAHJONG_DOT8, MAHJONG_DOT8,
	MAHJONG_DOT9, MAHJONG_DOT9, MAHJONG_DOT9, MAHJONG_DOT9,

	// 条
	MAHJONG_BAM1, MAHJONG_BAM1, MAHJONG_BAM1, MAHJONG_BAM1,
	MAHJONG_BAM2, MAHJONG_BAM2, MAHJONG_BAM2, MAHJONG_BAM2,
	MAHJONG_BAM3, MAHJONG_BAM3, MAHJONG_BAM3, MAHJONG_BAM3,
	MAHJONG_BAM4, MAHJONG_BAM4, MAHJONG_BAM4, MAHJONG_BAM4,
	MAHJONG_BAM5, MAHJONG_BAM5, MAHJONG_BAM5, MAHJONG_BAM5,
	MAHJONG_BAM6, MAHJONG_BAM6, MAHJONG_BAM6, MAHJONG_BAM6,
	MAHJONG_BAM7, MAHJONG_BAM7, MAHJONG_BAM7, MAHJONG_BAM7,
	MAHJONG_BAM8, MAHJONG_BAM8, MAHJONG_BAM8, MAHJONG_BAM8,
	MAHJONG_BAM9, MAHJONG_BAM9, MAHJONG_BAM9, MAHJONG_BAM9,
}

// MahjongCards36 36 张牌
var MahjongCards36 = []ID{
	// 万
	MAHJONG_CRAK1, MAHJONG_CRAK1, MAHJONG_CRAK1, MAHJONG_CRAK1,
	MAHJONG_CRAK2, MAHJONG_CRAK2, MAHJONG_CRAK2, MAHJONG_CRAK2,
	MAHJONG_CRAK3, MAHJONG_CRAK3, MAHJONG_CRAK3, MAHJONG_CRAK3,
	MAHJONG_CRAK4, MAHJONG_CRAK4, MAHJONG_CRAK4, MAHJONG_CRAK4,
	MAHJONG_CRAK5, MAHJONG_CRAK5, MAHJONG_CRAK5, MAHJONG_CRAK5,
	MAHJONG_CRAK6, MAHJONG_CRAK6, MAHJONG_CRAK6, MAHJONG_CRAK6,
	MAHJONG_CRAK7, MAHJONG_CRAK7, MAHJONG_CRAK7, MAHJONG_CRAK7,
	MAHJONG_CRAK8, MAHJONG_CRAK8, MAHJONG_CRAK8, MAHJONG_CRAK8,
	MAHJONG_CRAK9, MAHJONG_CRAK9, MAHJONG_CRAK9, MAHJONG_CRAK9,
}

// AllTiles 所有种类的牌 (不含花牌/季节牌，共34种)
// 用于遍历听牌
var AllTiles = []ID{
	// 万
	MAHJONG_CRAK1, MAHJONG_CRAK2, MAHJONG_CRAK3, MAHJONG_CRAK4, MAHJONG_CRAK5,
	MAHJONG_CRAK6, MAHJONG_CRAK7, MAHJONG_CRAK8, MAHJONG_CRAK9,
	// 筒
	MAHJONG_DOT1, MAHJONG_DOT2, MAHJONG_DOT3, MAHJONG_DOT4, MAHJONG_DOT5,
	MAHJONG_DOT6, MAHJONG_DOT7, MAHJONG_DOT8, MAHJONG_DOT9,
	// 条
	MAHJONG_BAM1, MAHJONG_BAM2, MAHJONG_BAM3, MAHJONG_BAM4, MAHJONG_BAM5,
	MAHJONG_BAM6, MAHJONG_BAM7, MAHJONG_BAM8, MAHJONG_BAM9,
	// 风
	MAHJONG_EAST, MAHJONG_SOUTH, MAHJONG_WEST, MAHJONG_NORTH,
	// 箭 (中发白)
	MAHJONG_RED, MAHJONG_GREE, MAHJONG_WHITE,
}
